FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /web
COPY requirements.txt /web

RUN set -ex \
    # && pip install -r requirements.txt \
    # python3 -m venv venv &&\
    # source ./venv/bin/activate &&\
    pip install -U pip &&\
    pip install --no-cache-dir -r /web/requirements.txt
# python3 manage.py migrate &&\
# python3 manage.py seed -a &&\
# python3 manage.py add-icons &&\
# python3 manage.py search_index --rebuild -f

COPY . /web

EXPOSE 8000


CMD [ "gunicorn", "--bind", ":8000", "--workers", "3", "core.wsgi.application" ]
