# Generated by Django 4.0.1 on 2022-03-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subscribe_delete_subscript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscription',
        ),
    ]
